name:       CSE 440 - Autumn 2014
baseurl:    /courses/cse440/14au

collections:
  assignments:
    output: true
  projects:
    output: false

exclude:
  - env27
  - env34
  - fabfile.py
  - fabfile.pyc
  - README.md
  - requirements2.txt
  - requirements3.txt
  - tests
